# Site settings
title: Christopher Cabezas
academic_email: christopher.cabezas at u-picardie.fr

description: > # this means to ignore newlines until "baseurl:"
  Dynamical Systems, Ergodic Theory, Symbolic Dynamics

baseurl: "" # the subpath of your site, e.g. /blog/

url: "https://elizabethmcd.github.io" # the base hostname & protocol for your site

github_username: christophercabezas
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html
